Models/Despesas/Despesa.cs
using System.ComponentModel.DataAnnotations;

namespace ControleDeDespesas.Models.Despesas
{
    public class Despesa
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(100)]
        public string Descricao { get; set; }
        public double Valor { get; set; }
        public DateTime Data { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ControleDeDespesas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DespesaController.cs
using ControleDeDespesas.DTOs;
using ControleDeDespesas.Models;
using ControleDeDespesas.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ControleDeDespesas.Controllers
{
    public class DespesaController : Controller
    {
        private readonly ILogger<DespesaController> _logger;
        private readonly IDespesaService _despesaService;

        public DespesaController(ILogger<DespesaController> logger, IDespesaService despesaService)
        {
            _logger = logger;
            _despesaService = despesaService;
        }

        public async Task<IActionResult> Index()
        {
            var listDespesaDto = new ListDespesaDTO();
            listDespesaDto.Items = await _despesaService.FindBy(listDespesaDto.DataInicial, listDespesaDto.DataFinal);

            return View(listDespesaDto);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Despesa/Index.cshtml
@model ControleDeDespesas.DTOs.ListDespesaDTO

@{
    ViewData["Title"] = "Home Page";
}
<div class="row">
    <div class="col-sm">
        <h1>Despesas</h1>
    </div>
</div>
@*
<div class="row">
    <div class="col-sm-12">
        <a asp-action="Create" asp-controller="Despesa" class="btn btn-primary btn-lg btn-block">Nova despesa</a>
    </div>
</div>
*@
<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input asp-for="DataInicial" type="date" placeholder="Digite a data inicial" class="form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <input asp-for="DataFinal" type="date" placeholder="Digite a data final" class="form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Buscar</button>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col=md">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descrição</th>
                    <th>Data</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.Items.Count > 0)
                {
                    foreach(var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Descricao</td>
                            <td>@item.Data.ToString("dd/MM/yyyy")</td>
                            <td>@item.Valor</td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="4">Nenhum registro encontrado.</td></tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControleDeDespesas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleDeDespesas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Despesa" asp-action="Index">ControleDeDespesas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesa" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ControleDeDespesas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>